# Generated by Django 4.2.8 on 2023-12-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_alter_restaurant_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantsPostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant', models.CharField(max_length=100, verbose_name='Enter your restaurants name')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='restaurants/')),
                ('cost', models.PositiveIntegerField()),
                ('genre', models.CharField(choices=[('Russian', 'Russian'), ('Italian', 'Italian'), ('American', 'American'), ('Japanese', 'Japanese'), ('Chinese', 'Chinese')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.TextField()),
                ('contact_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
