# Generated by Django 4.2.7 on 2023-11-22 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afisha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_film', models.CharField(max_length=100)),
                ('time_title', models.TimeField()),
                ('hall', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Enter your product name')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='products/')),
                ('cost', models.PositiveIntegerField()),
                ('genre', models.CharField(choices=[('Adults', 'Adults'), ('Babies', 'Babies')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RunString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Enter your title')),
                ('description', models.TextField(verbose_name='Enter your description')),
            ],
            options={
                'verbose_name': 'Ticker',
                'verbose_name_plural': 'Tickers',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.URLField()),
            ],
        ),
    ]
