# Generated by Django 5.0 on 2023-12-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
        migrations.RemoveField(
            model_name='person',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='person',
            name='hobby',
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='average_cost',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='contact_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='genre',
            field=models.CharField(choices=[('Russian', 'Russian'), ('Italian', 'Italian'), ('American', 'American'), ('Japanese', 'Japanese'), ('Chinese', 'Chinese')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='Enter your restaurants name'),
        ),
    ]
