# Generated by Django 5.0 on 2023-12-18 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0002_restaurant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
