# Generated by Django 5.0 on 2023-12-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantpostmodel',
            name='image',
            field=models.ImageField(upload_to='restaurants/'),
        ),
    ]
