# Generated by Django 4.2.8 on 2023-12-19 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_alter_restaurantpostmodel_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantpostmodel',
            old_name='restaurants',
            new_name='restaurant',
        ),
    ]
