# Generated by Django 4.2.8 on 2023-12-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0004_rename_restaurants_restaurantpostmodel_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='slider',
            name='width',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
