# Generated by Django 4.2.8 on 2023-12-20 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0005_slider_height_slider_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='height',
        ),
        migrations.RemoveField(
            model_name='slider',
            name='width',
        ),
    ]
