# Generated by Django 5.0 on 2023-12-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0006_remove_slider_height_remove_slider_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantpostmodel',
            name='genre',
            field=models.CharField(choices=[('Russian', 'Russian'), ('Italian', 'Italian'), ('Korean', 'Korean'), ('Japanese', 'Japanese'), ('Chinese', 'Chinese'), ('Kyrgyz', 'Kyrgyz'), ('Turkish', 'Turkish')], max_length=100),
        ),
    ]
